# -*- coding: utf-8 -*-
"""Cópia de Atividade.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1htj-QpauOe7ggF8W9YB10ZayxZw75Ehv
"""

import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
from sklearn.naive_bayes import MultinomialNB

# Carrega os dados
df = pd.read_csv('ultima_aula.csv', index_col=0)

# Divide os dados em variáveis independentes e dependentes
X = df['texto']
y = df['categoria']

# Vetorização
vectorizer = CountVectorizer(stop_words='english')
X = vectorizer.fit_transform(X)

# Divide em conjuntos de treinamento e teste
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Constrói o modelo
clf = MultinomialNB()
clf.fit(X_train, y_train)

# Faz as previsões
y_pred = clf.predict(X_test)

# Avalia o modelo
print(classification_report(y_test, y_pred))